services:
  minecraft:
    build: .
    container_name: minecraft
    ports:
      - 25565:25565
      - 25575:25575
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - MINECRAFT_VERSION=1.21.1
      - MINECRAFT_MEMORY=512M
    volumes:
      - ./data:/opt/minecraft/data
