version: "3"

services:
  minecraft_server:
    build: .
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
        - ./minecraft-data:/opt/minecraft