services:
  minecraft:
    build:
      context: .
      args:
        MINECRAFT_SERVER_VERSION: ${MINECRAFT_SERVER_VERSION}
    container_name: minecraft
    user: ${USER_ID}:${GROUP_ID}
    env_file: ./.env
    ports:
      - "${MINECRAFT_SERVER_PORT}:25565"
      - "${MINECRAFT_SERVER_RCON_PORT}:25575"
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - SERVER_INITIAL_MEMORY=${MINECRAFT_SERVER_INITIAL_MEMORY}
      - SERVER_MAX_MEMORY=${MINECRAFT_SERVER_MAX_MEMORY}
    volumes:
      - ${MINECRAFT_SERVER_DATA_FOLDER}:/opt/minecraft/data
